Repository ChargeUnity/TQS_ChargeUnity, pull requests merged in 2025-06, with the labels that each got.

#46 Ch 288 integrate maps into searches
  ChargeUnity/frontend/src/App.jsx
  ChargeUnity/frontend/src/DriverStations.jsx
  ChargeUnity/frontend/src/StationMap.jsx
Labels: enhancement, frontend

#52 CH-300 station was missing charger association
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/model/Charger.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/model/Station.java
Labels: frontend, backend

#51 CH-299-Create-dashboard-for-observability
  ChargeUnity/dashboards/jvm_micrometer.json
  ChargeUnity/docker-compose.yml
  ChargeUnity/grafana/provisioning/dashboards/dashboard.yml
  ChargeUnity/grafana/provisioning/dashboards/dashboards/JVM (Micrometer)-1748527409286.json
  ChargeUnity/grafana/provisioning/datasources/datasource.yml
Labels: backend

#58 Update deploy.yml
  .github/workflows/deploy.yml
Labels: bug

#57 Release v1.0.0
  .github/workflows/deploy.yml
  ChargeUnity/backend/loadTests/load-test.js
  ChargeUnity/backend/pom.xml
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/controller/BookingController.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/controller/ChargerController.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/model/Booking.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/model/Car.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/model/Charger.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/model/Driver.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/model/Station.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/model/Trip.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/repository/ChargerRepository.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/service/ChargerService.java
  ChargeUnity/backend/src/main/java/tqs/ChargeUnity/service/StationService.java
  ChargeUnity/backend/src/test/java/tqs/ChargeUnity/controller/ChargerControllerIT.java
  ChargeUnity/backend/src/test/java/tqs/ChargeUnity/controller/OperatorControllerIT.java
  ChargeUnity/backend/src/test/java/tqs/ChargeUnity/functional/steps/BookTimesSlotsSteps.java
  ChargeUnity/backend/src/test/java/tqs/ChargeUnity/functional/steps/UpdateChargerStatusSteps.java
  ChargeUnity/backend/src/test/resources/tqs/ChargeUnity/features/booktimeslots.feature
  ChargeUnity/backend/src/test/resources/tqs/ChargeUnity/features/updatestation.feature
  ChargeUnity/dashboards/jvm_micrometer.json
  ChargeUnity/docker-compose.yml
  ChargeUnity/frontend/config.js
  ChargeUnity/frontend/package-lock.json
  ChargeUnity/frontend/package.json
  ChargeUnity/frontend/src/App.jsx
  ChargeUnity/frontend/src/ChargerList.jsx
  ChargeUnity/frontend/src/ChargerListUser.jsx
  ChargeUnity/frontend/src/ChargerStatus.jsx
  ChargeUnity/frontend/src/CreateBooking.jsx
  ChargeUnity/frontend/src/DriverStations.jsx
  ChargeUnity/frontend/src/Operator.jsx
  ChargeUnity/frontend/src/OperatorDetail.jsx
  ChargeUnity/frontend/src/RegisterCharger.jsx
  ChargeUnity/frontend/src/StationMap.jsx
  ChargeUnity/frontend/vite.config.js
  ChargeUnity/grafana/provisioning/dashboards/dashboard.yml
  ChargeUnity/grafana/provisioning/dashboards/dashboards/JVM (Micrometer)-1748527409286.json
  ChargeUnity/grafana/provisioning/datasources/datasource.yml
Labels: documentation

#60 Update deploy.yml
  .github/workflows/deploy.yml
Labels: bug
